version: '2.2'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: terror_events
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: